Repository sams14/practee, pull requests merged in 2021-07, with the labels that each got.

#23 flash message
  Routes/users.js
  middlewares/passport.js
  server.js
  utils/Auth.js
  utils/password.js
  views/pages/Partial/flash-message.ejs
  views/pages/create-account.ejs
  views/pages/forgot-password.ejs
  views/pages/login.ejs
  views/pages/reset-password.ejs
  views/vimeoLogin.ejs
Labels: enhancement, help wanted

#27 Branch equalization
  server.js
Labels: enhancement

#29 Mailer bug fixed
  utils/password.js
Labels: bug

#31 Test
  Job Scheduler/report_mailer.py
  Job Scheduler/requirements.txt
  Job Scheduler/vimeo_uploader.py
  Routes/users.js
  server.js
Labels: bug, enhancement

#33 Stream management
  Job Scheduler/s3util.py
  Job Scheduler/vimeo_uploader.py
  Routes/practee.js
  utils/vimeoFolder.js
Labels: enhancement
